### PR TITLE
Use torch native triu_indices

### PR DESCRIPTION
**Pull request by Balandat**
Not sure if this is part of the latest stable release,let's see what Travis says...

### CODE REVIEW

**Comment by jacobrgardner** [comment]
Hm, I think the pdist function is actually unused now that I switched everything to use the JIT code. I found the pdist code to actually be quite a bit slower

**Comment by Balandat** [comment]
if it's unused let's kill it

**Comment by vishwakftw** [comment]
@Balandat `tril_indices` are `triu_indices` not part of the latest release. I believe this will have to wait until v1.1.

**Comment by Balandat** [comment]
Argh, not a fan of bugfix-only releases.... 

Anyway, if this is unused as @jacobrgardner indicated we should just scrap it altogether.

**Comment by gpleiss** [comment]
I can confirm that we no longer use `__pdist_dist`. I'll remove it.

**Pull request closed without merging**
