### PR TITLE
Remove Cholesky related TODO and cholesky_solve util function

### PR DESCRIPTION
**Pull request by vishwakftw**
Since PyTorch >= 1.1, I thought it would be appropriate to update / clear these.

### CODE REVIEW

**Comment by Balandat** [comment]
Thanks for the PR. There is a number of other call sites for `cholesky_solve` that need to be updated though - do you want to give that a shot or should we take care of it?

**Comment by vishwakftw** [comment]
I'll fix them, I'm sorry that I forgot about the call sites.

**Comment by vishwakftw** [comment]
@Balandat this should be good to go now.

**Comment by Balandat** [comment]
looks good, thanks!

**Pull request merged**
