### PR TITLE
New PyTorch version for travis

### PR DESCRIPTION
**Pull request by gpleiss**
Updating to 1.5

### CODE REVIEW

**Comment by gpleiss** [comment]
@Balandat @jacobrgardner I was making sure we were compatible with 1.5 before our new release. There's a really strange bug with the pyro integration that only happens with `MeanFieldVariationalStrategy` - and I threw in a very hacky fix for it.

Not sure if this is an issue with the new version of PyTorch (I know there's some changes to PyTorch optimizers related to inplace changes https://github.com/pytorch/pytorch/pull/33640 and https://github.com/pytorch/pytorch/pull/34211). It could also be an issue on Pyro's end - and I'm not really sure how to proceed debugging.

Since this seems to be an edge case I'm okay throwing in a temporary hacky fix that will hopefully get ironed out soon. Is this okay with you two?

**Comment by Balandat** [comment]
Curious what causes this. What exactly is the bug? Another possibility would be recent changes to type promotion, but it seems like the `ones_like` wouldn't affect that?

**Comment by gpleiss** [comment]
I was getting "one of the variables needed for gradient computation has been modified by an inplace operation." This was only happening with `MeanFieldVariationalDistribution`, not `Cholesky` or `Delta`.

The `MeanFieldVariationalDistribution` has the following line:

```python
# self._variational_stddev is a parameter
variance = self._variational_stddev.pow(2)  # This line is causing the issue
covar = DiagLazyTensor(variance)
```

If I removed the `.pow(2)` - everything worked. If I did `covar = CholLazyTensor(DiagLazyTensor(self._variational_stddev))` - everything worked. The current solution (multiplying `self._variational_stddev` by an all ones mask) works. Really not sure why this is failing.

**Comment by Balandat** [comment]
huh, weird

**Pull request merged**
