### PR TITLE
Make zero_mean_mvn samples work with arbirary sample_shapes

### PR DESCRIPTION
**Pull request by Balandat**
Makes this consistent with the torch interface, declutters some of the special casing by using shape arithmetic. This will be useful whenutilizing QMC base samples, in which case we can't just reshape
everyting into a big tensor but have to comply with batch / sample shape (because samples are not iid anymore).

It also enables sampling from multi-dimensional batch shapes in LazyTensors (once those are fully supported)

### CODE REVIEW

**Comment by Balandat** [comment]
The test for BatchRepeatLazyTensor fails b/c of an issue in matmul -- maybe someone who knows the implementation of BatchRepeatLazyTensor can take a look?

**Comment by gpleiss** [comment]
I can take a look tomorrow

**Comment by Balandat** [comment]
Ping? @gpleiss

**Comment by gpleiss** [comment]
Ooops sorry checking now!

**Comment by Balandat** [comment]
yeah that makes a lot of sense. Let me know how it goes. I also have some draft commits that allow sampling from degenerate MVNs that I'll stack on top of that.

**Comment by gpleiss** [comment]
Works pretty well! I'll open up a new PR.

**Comment by gpleiss** [comment]
Closing in favor of #481

**Pull request closed without merging**
