### PR TITLE
add smoke tests to two notebooks where it was missing

### PR DESCRIPTION
**Pull request by martinjankowiak**
the only GPUs i currently have access to are in the cloud so someone will need to re-run the CIQ notebook and push to this branch in order to get reasonable performance timings...

### CODE REVIEW

**Comment by jacobrgardner** [comment]
@martinjankowiak Haha -- I saw the timing results in the file changes before I saw your comment and it gave me a mini heart attack :-).

I'll rerun the notebook on a GPU and reupload it to this branch :+1:.

**Comment by gpleiss** [comment]
huh my gpu timings seem weird. Cholesky is exceptionally slow... @jacobrgardner maybe take a look?

**Comment by gpleiss** [comment]
Ah okay - it looks like the ill-conditioning makes Cholesky not work, so the samples have to be drawn with an eigendecomposition. Will merge after checks pass.

**Comment by Balandat** [comment]
The reason it takes so long is, sadly, pytorch error handling: https://github.com/pytorch/pytorch/issues/34272

**Pull request merged**
