### PR TITLE
Fix kernel memory usage

### PR DESCRIPTION
**Pull request by jacobrgardner**
See #434, #438, #439. The current kernels are significantly more numerically stable, but use too much memory. We need to achieve the best of both worlds here, as the memory problems prevent exact GPs from running on as large of datasets as they otherwise could, and the round-off problems in the memory efficient version of the kernel cause other problems.

### CODE REVIEW

**Comment by gpleiss** [comment]
Bleh.... okay I'll take a look

**Comment by jacobrgardner** [comment]
@Balandat @gpleiss This should be all set now! Here are the changes:

- Wherever possible, we use torch.pdist instead of our own distance computation. This includes the case when `x1` and `x2` are equal and non-batch, as well as the batch setting when using pytorch-nightly.

- When we have to fall back on our own distance computation, we make things more stable by zeroing out the diagonal manually and replacing any negative distances with 0. This is a well known trick for making kernels more stable (see e.g. the sklearn kernel implementations).

- When asking for just the diagonal from `covar_sq_dist` we return all zeros if `x1` and `x2` are equal.

**Comment by jacobrgardner** [comment]
@Balandat should be all set, other than the failures on pytorch master which seem unrelated. I'm looking in to this now.

I fixed the easy performance issues and the `RuntimeError` checking is smarter. 

Additionally, in cases where the kernel is called with `covar(x)` *and* the resulting `LazyEvaluatedKernelTensor` is not indexed in to, we skip the `torch.equals(x1, x2)` check. Calling `covar(x, x)` or slicing the kernel necessitates this check still. It's really not all that slow, and it's worth noting that using default settings a check of this cost is something we do every forward call already:
https://github.com/cornellius-gp/gpytorch/blob/ca8ea7ee1f7a6289f6bf16584319c86ecd6c83a1/gpytorch/models/exact_gp.py#L156

**Comment by jacobrgardner** [comment]
@Balandat Actually, the failing tests seem to pass on master but not on this branch. I've no idea how they are possibly related :-/

**Comment by jacobrgardner** [comment]
@Balandat I'll handle the `x1_eq_x2` case slightly smarter later

**Pull request merged**
