### PR TITLE
Use num_* consistently for attributes (breaking change)

### PR DESCRIPTION
**Pull request by gpleiss**
We previously had a mix of n_* and num_*. This makes everything consistent.

BREAKING CHANGES:
- IndexKernel: `n_tasks` -> `num_tasks`
- LCMKernel: `n_tasks` -> `num_tasks`
- MultitaskKernel: `n_tasks` -> `num_tasks`
- MultitaskGaussianLikelihood: `n_tasks` -> `num_tasks`
- SoftmaxLikelihood: `n_features` -> `num_features`
- MultitaskMean: `n_tasks` -> `num_tasks`
- VariationalMarginalLogLikelihood: `n_data` -> `num_data`
- SpectralMixtureKernel: `n_dimensions` -> `ard_num_dims`, `n_mixtures` -> `num_mixtures`

### CODE REVIEW

**Comment by gpleiss** [comment]
This PR is built on top of #307 - so that should be merged first.

**Comment by gpleiss** [comment]
This PR fixes #260

**Comment by jacobrgardner** [comment]
This is really hard to look through at the moment because it includes the diff of #307. That being said, it's a pretty simple change so I'm assuming I'll be happy with it. This does probably add more stuff to comb through the examples for to make sure they all work.

**Comment by gpleiss** [comment]
Yeah I'm combing through the examples now :)

**Comment by jacobrgardner** [comment]
Could we just do a quick rebase on to beta before merging now that #307 is merged if you want code review? This diff is awful, lol

**Comment by Balandat** [comment]
Before merging this in, can you update the tutorial notebooks to make sure they are consistent?

**Comment by gpleiss** [comment]
Working on it!

**Comment by gpleiss** [comment]
Updated all examples

**Pull request merged**
