### PR TITLE
Removed CachedCGLazyTensor, (deprecated) WhitenedVariationalStrategy

### LINKED ISSUE #1415: [Bug] Possible Memory Leak in UnwhitenedVariationalStrategy
# 🐛 Bug

This is a gpytorch-only issue reproducing https://github.com/pytorch/botorch/issues/641 . When using an `UnwhitenedVariationalStrategy`, it looks like something is building up in the (GPU) memory usage over multiple posterior calls that is causing out of memory issues.

## To reproduce

** Code snippet to reproduce **
```python
import torch
from gpytorch.kernels import MaternKernel, ScaleKernel
from gpytorch.means import ZeroMean

from gpytorch.models import ApproximateGP
from gpytorch.variational import CholeskyVariationalDistribution
from gpytorch.variational import UnwhitenedVariationalStrategy, VariationalStrategy

### define variational model
class VariationalGPModel(ApproximateGP):
    def __init__(self, inducing_points, likelihood, *args, **kwargs):
        variational_distribution = CholeskyVariationalDistribution(inducing_points.size(0))
        # this works
#         variational_strategy = VariationalStrategy(
#             self, inducing_points, variational_distribution, learn_inducing_locations=False
#         )       
        # this OOMs
        variational_strategy = UnwhitenedVariationalStrategy(
            self, inducing_points, variational_distribution, learn_inducing_locations=False
        )
        super(VariationalGPModel, self).__init__(variational_strategy)
        self.mean_module = ZeroMean()
        self.covar_module = ScaleKernel(
            MaternKernel(
                ard_num_dims=2,
                nu=0.5,
            ),
        )
        self.likelihood = likelihood

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)

#### run simulated BO loop
  if torch.cuda.is_available():
      device = torch.device("cuda:3")
  else:
      device = torch.device("cpu")
  
  current_x = torch.randn(10, 2, device=device)
  current_y = torch.randn(10, device=device)
  
  test_x = torch.randn(1000, 2, device=device)

  induc_points = torch.rand(900, 2)
  
  model = VariationalGPModel(
      inducing_points = induc_points,
      likelihood=None,
  ).to(device)

  for step in range(500):
      if step > 0 and step % 25 == 0:
          print("Beginning step ", step)

      start = time.time()
      model.train()
      model.zero_grad()
          
      model.eval()
      pred = model(test_x)
      vals, inds = pred.variance.sort()
      acq_value = vals[-5:].mean().detach()
      candidates = test_x[inds[-5:]]
      del candidates, vals, inds, pred
```

** Stack trace/error message **
```
~/gpytorch/gpytorch/models/approximate_gp.py in __call__(self, inputs, prior, **kwargs)
     79         if inputs.dim() == 1:
     80             inputs = inputs.unsqueeze(-1)
---> 81         return self.variational_strategy(inputs, prior=prior, **kwargs)

~/gpytorch/gpytorch/variational/_variational_strategy.py in __call__(self, x, prior, **kwargs)
    127                 inducing_values=variational_dist_u.mean,
    128                 variational_inducing_covar=variational_dist_u.lazy_covariance_matrix,
--> 129                 **kwargs,
    130             )
    131         elif isinstance(variational_dist_u, Delta):

~/gpytorch/gpytorch/module.py in __call__(self, *inputs, **kwargs)
     26 
     27     def __call__(self, *inputs, **kwargs):
---> 28         outputs = self.forward(*inputs, **kwargs)
     29         if isinstance(outputs, list):
     30             return [_validate_module_outputs(output) for output in outputs]

~/gpytorch/gpytorch/variational/unwhitened_variational_strategy.py in forward(self, x, inducing_points, inducing_values, variational_inducing_covar)
    131                     eager_rhs.detach(),
    132                     logdet_terms=(not cholesky),
--> 133                     include_tmats=(not settings.skip_logdet_forward.on() and not cholesky),
    134                 )
    135                 eager_rhss = [

~/gpytorch/gpytorch/lazy/cached_cg_lazy_tensor.py in precompute_terms(cls, base_lazy_tensor, eager_rhs, logdet_terms, include_tmats)
     67                         torch.cat([probe_vectors, eager_rhs], -1),
     68                         preconditioner=base_lazy_tensor._preconditioner()[0],
---> 69                         num_tridiag=probe_vectors.size(-1),
     70                     )
     71                 else:

~/gpytorch/gpytorch/lazy/lazy_tensor.py in _solve(self, rhs, preconditioner, num_tridiag)
    653             max_iter=settings.max_cg_iterations.value(),
    654             max_tridiag_iter=settings.max_lanczos_quadrature_iterations.value(),
--> 655             preconditioner=preconditioner,
    656         )
    657 

~/gpytorch/gpytorch/utils/linear_cg.py in linear_cg(matmul_closure, rhs, n_tridiag, tolerance, eps, stop_updating_after, max_iter, max_tridiag_iter, initial_guess, preconditioner)
    133         max_tridiag_iter = settings.max_lanczos_quadrature_iterations.value()
    134     if initial_guess is None:
--> 135         initial_guess = torch.zeros_like(rhs)
    136     if tolerance is None:
    137         if settings._use_eval_tolerance.on():

RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 3; 23.65 GiB total capacity; 21.73 GiB already allocated; 2.00 MiB free; 22.65 GiB reserved in total by PyTorch)
```

## Expected Behavior

It should not OOM like that.

## System information
Ubuntu 18.04. titan rtx gpu

**Please complete the following information:**
gpytorch 1.3.0, commit 4dec144de
pytorch 1.7.0

### PR DESCRIPTION
**Pull request by gpleiss**
- We should just use Cholesky for variational models.
- I took this PR as an opportunity to remove WhitenedVariationalStrategy, which has been deprecated for some time now (it was using CachedCGLT)

[Fixes #1415]

### CODE REVIEW

**Comment by gpleiss** [comment]
@jacobrgardner in this PR I'm completely removing CG-based unwhitened variational training. What do you think about this?

**Comment by gpleiss** [comment]
If we want to keep CG-based training, I think it would make the most sense to introduce a `CGUnwhitenedVariationalStrategy`, like how we have `CIQVariationalStrategy`. I think this makes sense for two reasons:

1. The internals will need to be quite different than what we currently have in `UnwhitenedVariationalStrategy` (since we'll have to manually cache the KL divergence calls).
2. The standard `max_cholesky_size` setting is optimized for ExactGP, and for the variational setting it would really depend on your batch size and other hypers.

I don't think there's a pressing need to add this. @wjmaddox do you think this would be needed for the BoTorch application in #1415 , or will Cholesky suffice?

**Comment by jacobrgardner** [comment]
Yeah, this is the way. I think at this point we're pretty clearly championing CIQ as the technology to use if you want to use iterative methods for SVI, since we are clearly championing whitened SVI. I'm definitely on board with abandoning standard CG for SVI entirely.

**Comment by gpleiss** [comment]
The only use case I can think of is if you want to do non-sparse variational methods (e.g. inducing points = data points), and you have ~10,000 data points.

**Review by Balandat — APPROVED** [review]
This generally lgtm and I don't think it should cause any issues on our end, though @wjmaddox would probably know better.

**Pull request merged**
