### PR TITLE
Increase num_trace_samples for test_spectral_mixture_gp_mean_abs_error

### PR DESCRIPTION
**Pull request by orionr**
Matches some fixes we needed when testing internally with pytorch on master branch.

cc @soumith

### CODE REVIEW

**Comment by jacobrgardner** [comment]
@orionr I'm in the process of looking in to the flakiness of this in general, it looks like there are some minor issues with the SM kernel that have popped up.

**Comment by Balandat** [comment]
@jacobrgardner can we kill this PR?

**Comment by jacobrgardner** [comment]
Yeah. I couldn't get the seed change working for Travis, but I'm happy to merge or close as you see fit.

**Comment by Balandat** [comment]
Either way works, I don't think we're currently seeing issues with this.

**Comment by Balandat** [comment]
I guess we can kill this?

**Pull request closed without merging**
