### PR TITLE
updated the docs for constraints

### PR DESCRIPTION
**Pull request by ashwin0630**
### docs compiled locally without any warning
 
#640 

Screenshot (3)

Screenshot (4)

Screenshot (5)

Screenshot (6)

### CODE REVIEW

**Comment by Balandat** [comment]
Hi @ashwin0630, would you mind adding an explanation to @jackbuck's question about what happens when `transform` is set to `None`. You can base this off my response in this comment: https://github.com/cornellius-gp/gpytorch/issues/2242#issuecomment-1399303074

Thanks!

**Review by gpleiss — CHANGES_REQUESTED** [review]
@ashwin0630 if you notice, your documentation is still failing on our CI: https://readthedocs.org/projects/gpytorch/builds/19195054/

We have strict checking that ensures that documentation builds do not throw any warnings (your docs are throwing 3 warnings). It is likely that your build locally succeeds (i.e. no errors) but is still throwing warnings.

In addition to @Balandat 's request, can you fix the documentation warnings?

**Comment by gpleiss** [comment]
@ashwin0630 any updates on this PR? It would be great to get this into the repo.

**Comment by ashwin0630** [comment]
as iam struck and new can u help to sort the problem please @gpleiss

**Pull request closed without merging**
