### PR TITLE
[Examples] Fix Simple GP function noise

### PR DESCRIPTION
**Pull request by sdsingh**
The function stated in the Simple GP example (https://gpytorch.readthedocs.io/en/latest/examples/01_Exact_GPs/Simple_GP_Regression.html#Introduction)
 has noise from a Gaussian with variance 0.2. 

However, the following code block samples from a Gaussian with _standard deviation_ 0.2. This makes the code snippet/sample consistent with the definition stated in the introduction.

### CODE REVIEW

**Comment by Balandat** [comment]
Did you run the full nb though? seems like none of the outputs were updated. Might be easier to just update the text to use standard dev.

**Comment by jacobrgardner** [comment]
Looking at it in the notebook, I think it might be better to just update the text to say standard deviation as Max said. The function just looks pretty noisy with twice-and-a-bit as much noise.

**Comment by sdsingh** [comment]
Sounds good to me!

**Comment by sdsingh** [comment]
I squashed/force-pushed since there's not much of an interesting commit history here, hopefully that's ok! Updated the text + the code sample to make the variance/standard deviation a bit clearer.

**Pull request merged**
